project:
  type: website

website:
  title: "EPL Penalty Kick Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Dataset
      - href: about.qmd
        text: About
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



